# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{itunes-connect}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Vollmer"]
  s.date = %q{2009-11-07}
  s.default_executable = %q{itunes_connect}
  s.description = %q{Programmatic and command-line access to iTunes Connect Reports}
  s.email = %q{alex.vollmer@gmail.com}
  s.executables = ["itunes_connect"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "bin/itunes_connect",
     "lib/itunes_connect.rb",
     "lib/itunes_connect/commands.rb",
     "lib/itunes_connect/commands/download.rb",
     "lib/itunes_connect/commands/help.rb",
     "lib/itunes_connect/commands/import.rb",
     "lib/itunes_connect/commands/report.rb",
     "lib/itunes_connect/connection.rb",
     "lib/itunes_connect/rc_file.rb",
     "lib/itunes_connect/report.rb",
     "lib/itunes_connect/store.rb",
     "spec/commands/download_spec.rb",
     "spec/commands/help_spec.rb",
     "spec/commands/import_spec.rb",
     "spec/commands/report_spec.rb",
     "spec/commands_spec.rb",
     "spec/connection_spec.rb",
     "spec/fakeweb/homepage",
     "spec/fixtures/report.txt",
     "spec/report_spec.rb",
     "spec/spec_helper.rb",
     "spec/store_spec.rb"
  ]
  s.homepage = %q{http://github.com/alexvollmer/itunes-connect}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Get your iTunes Connect Reports}
  s.test_files = [
    "spec/commands/download_spec.rb",
     "spec/commands/help_spec.rb",
     "spec/commands/import_spec.rb",
     "spec/commands/report_spec.rb",
     "spec/commands_spec.rb",
     "spec/connection_spec.rb",
     "spec/report_spec.rb",
     "spec/spec_helper.rb",
     "spec/store_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httpclient>, ["~> 2.1"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.3"])
      s.add_runtime_dependency(%q<clip>, [">= 1.0.1"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, ["~> 1.2"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<httpclient>, ["~> 2.1"])
      s.add_dependency(%q<nokogiri>, ["~> 1.3"])
      s.add_dependency(%q<clip>, [">= 1.0.1"])
      s.add_dependency(%q<sqlite3-ruby>, ["~> 1.2"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<httpclient>, ["~> 2.1"])
    s.add_dependency(%q<nokogiri>, ["~> 1.3"])
    s.add_dependency(%q<clip>, [">= 1.0.1"])
    s.add_dependency(%q<sqlite3-ruby>, ["~> 1.2"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end

